# Generated by Django 3.1.1 on 2020-09-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=264, unique=True)),
                ('name', models.CharField(max_length=264)),
                ('brand', models.CharField(max_length=264)),
                ('country', models.CharField(max_length=264)),
                ('chain', models.CharField(max_length=264)),
                ('category', models.CharField(max_length=264)),
                ('sex', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
