# Generated by Django 3.1.1 on 2020-09-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_product_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='create_time',
            new_name='created',
        ),
    ]
